/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mgh.edd.app;

class MessageUtils {
    public static String getMessage() {
        return "git es una palicacion que te permite editar desde cualqier lado y modificarlo en todos los equipos que este ese repositorio";
    }
}
